### ISSUE TITLE
Cannot forward body

### ISSUE THREAD

**Issue by JsanchezPilo** [udleinati/kong-plugin-the-middleman#1]
Hi thanks for the plugin, may i use it in production envirment?, it is not possible to forward body, thanks in advance

**Comment by udleinati** [comment]
@JsanchezPilo yes, we are using it in a production environment and so far everything is going pretty well. I just accepted your PR, I'll create a new release on luarocks later.

**Comment by udleinati** [comment]
kong-plugin-the-middleman 1.0.2 released
