### ISSUE TITLE
Expected value but found invalid token at character 1

### ISSUE THREAD

**Issue by abdulrazakbg** [udleinati/kong-plugin-the-middleman#3]
Hi,

Getting below error while receiving response from the middle-service

`2021/10/22 06:51:04 [error] 1098#0: *250 [kong] init.lua:282 [the-middleman] ...ocal/share/lua/5.1/kong/plugins/the-middleman/access.lua:81: Expected value but found invalid token at character 1, client: 127.0.0.1, server: kong, request: "GET /maps/my-app/places HTTP/1.1", host: "localhost:8080`

Plugin config :
`apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-middle-the-man
config: 
  url: http://kong-my-app.default:8200/my-app/places/sample
  method: GET
plugin: the-middleman`

Sample response from service : `{
    "tenantId": "123",
    "role": "admin",
    "accountId": "112233"
}`

**Comment by joelsdc** [comment]
Are you sure your sample response is a valid JSON?

Either way, something like this might be useful: https://stackoverflow.com/questions/16912606/how-to-capture-error-message-from-third-party-library-in-lua
